import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { DialogFooter } from "@/components/ui/dialog";
import LoginProvider from "./_context/LoginContext";
import CartProvider from "./_context/CartContext";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <LoginProvider>
          <CartProvider>
          <Header />
          {children}
          <Footer />
          </CartProvider>
        </LoginProvider>
      </body>
    </html>
  );
}
